CREATE TABLE gioss_index_reporte_ips_2463
(
  entidad_reportante character varying(12) NOT NULL,
  entidad_a_reportar character varying(90) NOT NULL,
  fecha_inicio_periodo date NOT NULL,
  fecha_de_corte date NOT NULL,
  fecha_y_hora_validacion timestamp without time zone NOT NULL,
  nombre_archivo character varying(320) NOT NULL,
  numero_de_secuencia integer,
  prestador_en_archivo character varying(12) NOT NULL,
  nit_prestador_en_archivo character varying(20),
  nombre_prestador character varying(320),
  codigo_departamento character varying(2),
  codigo_municipio character varying(5),
  cantidad_lineas_en_archivo character varying(320),
  cantidad_lineas_correctas_en_archivo character varying(320),
  cantidad_inconsistencias_para_ips character varying(320),
  PRIMARY KEY (entidad_reportante, entidad_a_reportar, fecha_inicio_periodo, fecha_de_corte, nombre_archivo, fecha_y_hora_validacion, prestador_en_archivo)
);

CREATE TABLE gioss_indice_archivo_para_analisis_2463
(
  cod_prestador_servicios_salud character varying(12) NOT NULL,
  codigo_eapb character varying(90) NOT NULL,
  fecha_inicio_periodo date NOT NULL,
  fecha_de_corte date NOT NULL,
  fecha_y_hora_validacion timestamp without time zone NOT NULL,
  nombre_archivo character varying(320) NOT NULL,
  numero_de_secuencia integer,
  PRIMARY KEY (cod_prestador_servicios_salud, codigo_eapb, fecha_inicio_periodo, fecha_de_corte, nombre_archivo, fecha_y_hora_validacion)
);

CREATE TABLE gioss_archivo_para_analisis_2463
(
  cod_prestador_servicios_salud character varying(12) NOT NULL,
  codigo_eapb character varying(90) NOT NULL,
  fecha_inicio_periodo date NOT NULL,
  fecha_de_corte date NOT NULL,
  fecha_y_hora_validacion timestamp without time zone NOT NULL,
  nombre_archivo character varying(320) NOT NULL,
  numero_fila bigint NOT NULL,
  numero_de_secuencia integer,
  edad_years integer,
  edad_meses integer,
  edad_dias integer,
  regional character varying(320),
  grupo_etareo integer,
  grupo_edad_quinquenal integer,
  campo_erc_de_numero_orden_0 character varying(320),
  campo_erc_de_numero_orden_1 character varying(320),
  campo_erc_de_numero_orden_2 character varying(320),
  campo_erc_de_numero_orden_3 character varying(320),
  campo_erc_de_numero_orden_4 character varying(320),
  campo_erc_de_numero_orden_5 character varying(320),
  campo_erc_de_numero_orden_6 character varying(320),
  campo_erc_de_numero_orden_7 character varying(320),
  campo_erc_de_numero_orden_8 character varying(320),
  campo_erc_de_numero_orden_9 character varying(320),
  campo_erc_de_numero_orden_10 character varying(320),
  campo_erc_de_numero_orden_11 character varying(320),
  campo_erc_de_numero_orden_12 character varying(320),
  campo_erc_de_numero_orden_13 character varying(320),
  campo_erc_de_numero_orden_14 character varying(320),
  campo_erc_de_numero_orden_15 character varying(320),
  campo_erc_de_numero_orden_16 character varying(320),
  campo_erc_de_numero_orden_17 character varying(320),
  campo_erc_de_numero_orden_18 character varying(320),
  campo_erc_de_numero_orden_19 character varying(320),
  campo_erc_de_numero_orden_20 character varying(320),
  campo_erc_de_numero_orden_21 character varying(320),
  campo_erc_de_numero_orden_22 character varying(320),
  campo_erc_de_numero_orden_23 character varying(320),
  campo_erc_de_numero_orden_24 character varying(320),
  campo_erc_de_numero_orden_25 character varying(320),
  campo_erc_de_numero_orden_26 character varying(320),
  campo_erc_de_numero_orden_27 character varying(320),
  campo_erc_de_numero_orden_28 character varying(320),
  campo_erc_de_numero_orden_29 character varying(320),
  campo_erc_de_numero_orden_30 character varying(320),
  campo_erc_de_numero_orden_31 character varying(320),
  campo_erc_de_numero_orden_32 character varying(320),
  campo_erc_de_numero_orden_33 character varying(320),
  campo_erc_de_numero_orden_34 character varying(320),
  campo_erc_de_numero_orden_35 character varying(320),
  campo_erc_de_numero_orden_36 character varying(320),
  campo_erc_de_numero_orden_37 character varying(320),
  campo_erc_de_numero_orden_38 character varying(320),
  campo_erc_de_numero_orden_39 character varying(320),
  campo_erc_de_numero_orden_40 character varying(320),
  campo_erc_de_numero_orden_41 character varying(320),
  campo_erc_de_numero_orden_42 character varying(320),
  campo_erc_de_numero_orden_43 character varying(320),
  campo_erc_de_numero_orden_44 character varying(320),
  campo_erc_de_numero_orden_45 character varying(320),
  campo_erc_de_numero_orden_46 character varying(320),
  campo_erc_de_numero_orden_47 character varying(320),
  campo_erc_de_numero_orden_48 character varying(320),
  campo_erc_de_numero_orden_49 character varying(320),
  campo_erc_de_numero_orden_50 character varying(320),
  campo_erc_de_numero_orden_51 character varying(320),
  campo_erc_de_numero_orden_52 character varying(320),
  campo_erc_de_numero_orden_53 character varying(320),
  campo_erc_de_numero_orden_54 character varying(320),
  campo_erc_de_numero_orden_55 character varying(320),
  campo_erc_de_numero_orden_56 character varying(320),
  campo_erc_de_numero_orden_57 character varying(320),
  campo_erc_de_numero_orden_58 character varying(320),
  campo_erc_de_numero_orden_59 character varying(320),
  campo_erc_de_numero_orden_60 character varying(320),
  campo_erc_de_numero_orden_61 character varying(320),
  campo_erc_de_numero_orden_62 character varying(320),
  campo_erc_de_numero_orden_63 character varying(320),
  campo_erc_de_numero_orden_64 character varying(320),
  campo_erc_de_numero_orden_65 character varying(320),
  campo_erc_de_numero_orden_66 character varying(320),
  campo_erc_de_numero_orden_67 character varying(320),
  campo_erc_de_numero_orden_68 character varying(320),
  campo_erc_de_numero_orden_69 character varying(320),
  campo_erc_de_numero_orden_70 character varying(320),
  campo_erc_de_numero_orden_71 character varying(320),
  campo_erc_de_numero_orden_72 character varying(320),
  campo_erc_de_numero_orden_73 character varying(320),
  campo_erc_de_numero_orden_74 character varying(320),
  campo_erc_de_numero_orden_75 character varying(320),
  campo_erc_de_numero_orden_76 character varying(320),
  campo_erc_de_numero_orden_77 character varying(320),
  campo_erc_de_numero_orden_78 character varying(320),
  campo_erc_de_numero_orden_79 character varying(320),
  campo_erc_de_numero_orden_80 character varying(320),
  campo_erc_de_numero_orden_81 character varying(320),
  campo_erc_de_numero_orden_82 character varying(320),
  campo_erc_de_numero_orden_83 character varying(320),
  campo_erc_de_numero_orden_84 character varying(320),
  campo_erc_de_numero_orden_85 character varying(320),
  campo_erc_de_numero_orden_86 character varying(320),
  campo_erc_de_numero_orden_87 character varying(320),
  campo_erc_de_numero_orden_88 character varying(320),
  campo_erc_de_numero_orden_89 character varying(320),
  campo_erc_de_numero_orden_90 character varying(320),
  campo_erc_de_numero_orden_91 character varying(320),
  campo_erc_de_numero_orden_92 character varying(320),
  campo_erc_de_numero_orden_93 character varying(320),
  campo_erc_de_numero_orden_94 character varying(320),
  campo_erc_de_numero_orden_95 character varying(320),
  campo_erc_de_numero_orden_96 character varying(320),
  campo_erc_de_numero_orden_97 character varying(320),
  campo_erc_de_numero_orden_98 character varying(320),
  campo_erc_de_numero_orden_99 character varying(320),
  campo_erc_de_numero_orden_100 character varying(320),
  campo_erc_de_numero_orden_101 character varying(320),
  campo_erc_de_numero_orden_102 character varying(320),
  campo_erc_de_numero_orden_103 character varying(320),
  campo_erc_de_numero_orden_104 character varying(320),
  campo_erc_de_numero_orden_105 character varying(320),
  campo_erc_de_numero_orden_106 character varying(320),
  campo_erc_de_numero_orden_107 character varying(320),
  campo_erc_de_numero_orden_108 character varying(320),
  campo_erc_de_numero_orden_109 character varying(320),
  campo_erc_de_numero_orden_110 character varying(320),
  campo_erc_de_numero_orden_111 character varying(320),
  campo_erc_de_numero_orden_112 character varying(320),
  campo_erc_de_numero_orden_113 character varying(320),
  campo_erc_de_numero_orden_114 character varying(320),
  campo_erc_de_numero_orden_115 character varying(320),
  campo_erc_de_numero_orden_116 character varying(320),
  campo_erc_de_numero_orden_117 character varying(320),
  campo_erc_de_numero_orden_118 character varying(320),
  PRIMARY KEY (cod_prestador_servicios_salud, codigo_eapb, fecha_inicio_periodo, fecha_de_corte, numero_fila, nombre_archivo, fecha_y_hora_validacion)
);