-- Table: gioss_archivo_para_analisis_4505

-- DROP TABLE gioss_indice_archivo_para_analisis_4505;
-- DROP TABLE gioss_archivo_para_analisis_4505;
CREATE TABLE gioss_indice_archivo_para_analisis_4505
(
  cod_prestador_servicios_salud character varying(12) NOT NULL,
  codigo_eapb character varying(90) NOT NULL,
  fecha_inicio_periodo date NOT NULL,
  fecha_de_corte date NOT NULL,
  fecha_y_hora_validacion timestamp NOT NULL,  
  nombre_archivo character varying(320) NOT NULL,
   PRIMARY KEY (cod_prestador_servicios_salud, codigo_eapb, fecha_inicio_periodo, fecha_de_corte, nombre_archivo, fecha_y_hora_validacion)
);

ALTER TABLE gioss_indice_archivo_para_analisis_4505 ADD COLUMN numero_de_secuencia integer;

CREATE TABLE gioss_archivo_para_analisis_4505
(
  cod_prestador_servicios_salud character varying(12) NOT NULL,
  codigo_eapb character varying(90) NOT NULL,
  fecha_inicio_periodo date NOT NULL,
  fecha_de_corte date NOT NULL,
  fecha_y_hora_validacion timestamp NOT NULL,  
  nombre_archivo character varying(320) NOT NULL,
  numero_fila bigint NOT NULL,
  edad_years integer,
  edad_meses integer,
  edad_dias integer,
  regional character varying(320),
  grupo_etareo integer,
  grupo_edad_quinquenal integer,
  campo0 character varying(320) NOT NULL,
  campo1 character varying(320) NOT NULL,
  campo2 character varying(320) NOT NULL,
  campo3 character varying(320) NOT NULL,
  campo4 character varying(320) NOT NULL,
  campo5 character varying(320) NOT NULL,
  campo6 character varying(320) NOT NULL,
  campo7 character varying(320) NOT NULL,
  campo8 character varying(320) NOT NULL,
  campo9 character varying(320) NOT NULL,
  campo10 character varying(320) NOT NULL,
  campo11 character varying(320) NOT NULL,
  campo12 character varying(320) NOT NULL,
  campo13 character varying(320) NOT NULL,
  campo14 character varying(320) NOT NULL,
  campo15 character varying(320) NOT NULL,
  campo16 character varying(320) NOT NULL,
  campo17 character varying(320) NOT NULL,
  campo18 character varying(320) NOT NULL,
  campo19 character varying(320) NOT NULL,
  campo20 character varying(320) NOT NULL,
  campo21 character varying(320) NOT NULL,
  campo22 character varying(320) NOT NULL,
  campo23 character varying(320) NOT NULL,
  campo24 character varying(320) NOT NULL,
  campo25 character varying(320) NOT NULL,
  campo26 character varying(320) NOT NULL,
  campo27 character varying(320) NOT NULL,
  campo28 character varying(320) NOT NULL,
  campo29 character varying(320) NOT NULL,
  campo30 character varying(320) NOT NULL,
  campo31 character varying(320) NOT NULL,
  campo32 character varying(320) NOT NULL,
  campo33 character varying(320) NOT NULL,
  campo34 character varying(320) NOT NULL,
  campo35 character varying(320) NOT NULL,
  campo36 character varying(320) NOT NULL,
  campo37 character varying(320) NOT NULL,
  campo38 character varying(320) NOT NULL,
  campo39 character varying(320) NOT NULL,
  campo40 character varying(320) NOT NULL,
  campo41 character varying(320) NOT NULL,
  campo42 character varying(320) NOT NULL,
  campo43 character varying(320) NOT NULL,
  campo44 character varying(320) NOT NULL,
  campo45 character varying(320) NOT NULL,
  campo46 character varying(320) NOT NULL,
  campo47 character varying(320) NOT NULL,
  campo48 character varying(320) NOT NULL,
  campo49 character varying(320) NOT NULL,
  campo50 character varying(320) NOT NULL,
  campo51 character varying(320) NOT NULL,
  campo52 character varying(320) NOT NULL,
  campo53 character varying(320) NOT NULL,
  campo54 character varying(320) NOT NULL,
  campo55 character varying(320) NOT NULL,
  campo56 character varying(320) NOT NULL,
  campo57 character varying(320) NOT NULL,
  campo58 character varying(320) NOT NULL,
  campo59 character varying(320) NOT NULL,
  campo60 character varying(320) NOT NULL,
  campo61 character varying(320) NOT NULL,
  campo62 character varying(320) NOT NULL,
  campo63 character varying(320) NOT NULL,
  campo64 character varying(320) NOT NULL,
  campo65 character varying(320) NOT NULL,
  campo66 character varying(320) NOT NULL,
  campo67 character varying(320) NOT NULL,
  campo68 character varying(320) NOT NULL,
  campo69 character varying(320) NOT NULL,
  campo70 character varying(320) NOT NULL,
  campo71 character varying(320) NOT NULL,
  campo72 character varying(320) NOT NULL,
  campo73 character varying(320) NOT NULL,
  campo74 character varying(320) NOT NULL,
  campo75 character varying(320) NOT NULL,
  campo76 character varying(320) NOT NULL,
  campo77 character varying(320) NOT NULL,
  campo78 character varying(320) NOT NULL,
  campo79 character varying(320) NOT NULL,
  campo80 character varying(320) NOT NULL,
  campo81 character varying(320) NOT NULL,
  campo82 character varying(320) NOT NULL,
  campo83 character varying(320) NOT NULL,
  campo84 character varying(320) NOT NULL,
  campo85 character varying(320) NOT NULL,
  campo86 character varying(320) NOT NULL,
  campo87 character varying(320) NOT NULL,
  campo88 character varying(320) NOT NULL,
  campo89 character varying(320) NOT NULL,
  campo90 character varying(320) NOT NULL,
  campo91 character varying(320) NOT NULL,
  campo92 character varying(320) NOT NULL,
  campo93 character varying(320) NOT NULL,
  campo94 character varying(320) NOT NULL,
  campo95 character varying(320) NOT NULL,
  campo96 character varying(320) NOT NULL,
  campo97 character varying(320) NOT NULL,
  campo98 character varying(320) NOT NULL,
  campo99 character varying(320) NOT NULL,
  campo100 character varying(320) NOT NULL,
  campo101 character varying(320) NOT NULL,
  campo102 character varying(320) NOT NULL,
  campo103 character varying(320) NOT NULL,
  campo104 character varying(320) NOT NULL,
  campo105 character varying(320) NOT NULL,
  campo106 character varying(320) NOT NULL,
  campo107 character varying(320) NOT NULL,
  campo108 character varying(320) NOT NULL,
  campo109 character varying(320) NOT NULL,
  campo110 character varying(320) NOT NULL,
  campo111 character varying(320) NOT NULL,
  campo112 character varying(320) NOT NULL,
  campo113 character varying(320) NOT NULL,
  campo114 character varying(320) NOT NULL,
  campo115 character varying(320) NOT NULL,
  campo116 character varying(320) NOT NULL,
  campo117 character varying(320) NOT NULL,
  campo118 character varying(320) NOT NULL,  
  PRIMARY KEY (cod_prestador_servicios_salud, codigo_eapb, fecha_inicio_periodo, fecha_de_corte, numero_fila, nombre_archivo, fecha_y_hora_validacion)
);

ALTER TABLE gioss_archivo_para_analisis_4505 ADD COLUMN numero_de_secuencia integer;

CREATE TABLE valores_permitidos_4505
(
  numero_campo_norma character varying(320) NOT NULL,
  nombre_campo character varying(320) NOT NULL,
  lista_valores_permitidos character varying(4000) NOT NULL,
  PRIMARY KEY(numero_campo_norma)
);