CREATE TABLE gioss_index_reporte_ips_0247
(
  entidad_reportante character varying(12) NOT NULL,
  entidad_a_reportar character varying(90) NOT NULL,
  fecha_inicio_periodo date NOT NULL,
  fecha_de_corte date NOT NULL,
  fecha_y_hora_validacion timestamp without time zone NOT NULL,
  nombre_archivo character varying(320) NOT NULL,
  numero_de_secuencia integer,
  prestador_en_archivo character varying(12) NOT NULL,
  nit_prestador_en_archivo character varying(20),
  nombre_prestador character varying(320),
  codigo_departamento character varying(2),
  codigo_municipio character varying(5),
  cantidad_lineas_en_archivo character varying(320),
  cantidad_lineas_correctas_en_archivo character varying(320),
  cantidad_inconsistencias_para_ips character varying(320),
  PRIMARY KEY (entidad_reportante, entidad_a_reportar, fecha_inicio_periodo, fecha_de_corte, nombre_archivo, fecha_y_hora_validacion, prestador_en_archivo)
);

CREATE TABLE gioss_indice_archivo_para_analisis_0247
(
  cod_prestador_servicios_salud character varying(12) NOT NULL,
  codigo_eapb character varying(90) NOT NULL,
  fecha_inicio_periodo date NOT NULL,
  fecha_de_corte date NOT NULL,
  fecha_y_hora_validacion timestamp without time zone NOT NULL,
  nombre_archivo character varying(320) NOT NULL,
  numero_de_secuencia integer,
  PRIMARY KEY (cod_prestador_servicios_salud, codigo_eapb, fecha_inicio_periodo, fecha_de_corte, nombre_archivo, fecha_y_hora_validacion)
);

CREATE TABLE gioss_archivo_para_analisis_0247
(
  cod_prestador_servicios_salud character varying(12) NOT NULL,
  codigo_eapb character varying(90) NOT NULL,
  fecha_inicio_periodo date NOT NULL,
  fecha_de_corte date NOT NULL,
  fecha_y_hora_validacion timestamp without time zone NOT NULL,
  nombre_archivo character varying(320) NOT NULL,
  numero_fila bigint NOT NULL,
  numero_de_secuencia integer,
  edad_years integer,
  edad_meses integer,
  edad_dias integer,
  regional character varying(320),
  grupo_etareo integer,
  grupo_edad_quinquenal integer,
  campo_cancer_de_numero_orden_1 character varying(320),
  campo_cancer_de_numero_orden_2 character varying(320),
  campo_cancer_de_numero_orden_3 character varying(320),
  campo_cancer_de_numero_orden_4 character varying(320),
  campo_cancer_de_numero_orden_5 character varying(320),
  campo_cancer_de_numero_orden_6 character varying(320),
  campo_cancer_de_numero_orden_7 character varying(320),
  campo_cancer_de_numero_orden_8 character varying(320),
  campo_cancer_de_numero_orden_9 character varying(320),
  campo_cancer_de_numero_orden_10 character varying(320),
  campo_cancer_de_numero_orden_11 character varying(320),
  campo_cancer_de_numero_orden_12 character varying(320),
  campo_cancer_de_numero_orden_13 character varying(320),
  campo_cancer_de_numero_orden_14 character varying(320),
  campo_cancer_de_numero_orden_15 character varying(320),
  campo_cancer_de_numero_orden_16 character varying(320),
  campo_cancer_de_numero_orden_17 character varying(320),
  campo_cancer_de_numero_orden_18 character varying(320),
  campo_cancer_de_numero_orden_19 character varying(320),
  campo_cancer_de_numero_orden_20 character varying(320),
  campo_cancer_de_numero_orden_21 character varying(320),
  campo_cancer_de_numero_orden_22 character varying(320),
  campo_cancer_de_numero_orden_23 character varying(320),
  campo_cancer_de_numero_orden_24 character varying(320),
  campo_cancer_de_numero_orden_25 character varying(320),
  campo_cancer_de_numero_orden_26 character varying(320),
  campo_cancer_de_numero_orden_27 character varying(320),
  campo_cancer_de_numero_orden_28 character varying(320),
  campo_cancer_de_numero_orden_29 character varying(320),
  campo_cancer_de_numero_orden_30 character varying(320),
  campo_cancer_de_numero_orden_31 character varying(320),
  campo_cancer_de_numero_orden_32 character varying(320),
  campo_cancer_de_numero_orden_33 character varying(320),
  campo_cancer_de_numero_orden_34 character varying(320),
  campo_cancer_de_numero_orden_35 character varying(320),
  campo_cancer_de_numero_orden_36 character varying(320),
  campo_cancer_de_numero_orden_37 character varying(320),
  campo_cancer_de_numero_orden_38 character varying(320),
  campo_cancer_de_numero_orden_39 character varying(320),
  campo_cancer_de_numero_orden_40 character varying(320),
  campo_cancer_de_numero_orden_41 character varying(320),
  campo_cancer_de_numero_orden_42 character varying(320),
  campo_cancer_de_numero_orden_43 character varying(320),
  campo_cancer_de_numero_orden_44 character varying(320),
  campo_cancer_de_numero_orden_45 character varying(320),
  campo_cancer_de_numero_orden_46 character varying(320),
  campo_cancer_de_numero_orden_47 character varying(320),
  campo_cancer_de_numero_orden_48 character varying(320),
  campo_cancer_de_numero_orden_49 character varying(320),
  campo_cancer_de_numero_orden_50 character varying(320),
  campo_cancer_de_numero_orden_51 character varying(320),
  campo_cancer_de_numero_orden_52 character varying(320),
  campo_cancer_de_numero_orden_53 character varying(320),
  campo_cancer_de_numero_orden_54 character varying(320),
  campo_cancer_de_numero_orden_55 character varying(320),
  campo_cancer_de_numero_orden_56 character varying(320),
  campo_cancer_de_numero_orden_57 character varying(320),
  campo_cancer_de_numero_orden_58 character varying(320),
  campo_cancer_de_numero_orden_59 character varying(320),
  campo_cancer_de_numero_orden_60 character varying(320),
  campo_cancer_de_numero_orden_61 character varying(320),
  campo_cancer_de_numero_orden_62 character varying(320),
  campo_cancer_de_numero_orden_63 character varying(320),
  campo_cancer_de_numero_orden_64 character varying(320),
  campo_cancer_de_numero_orden_65 character varying(320),
  campo_cancer_de_numero_orden_66 character varying(320),
  campo_cancer_de_numero_orden_67 character varying(320),
  campo_cancer_de_numero_orden_68 character varying(320),
  campo_cancer_de_numero_orden_69 character varying(320),
  campo_cancer_de_numero_orden_70 character varying(320),
  campo_cancer_de_numero_orden_71 character varying(320),
  campo_cancer_de_numero_orden_72 character varying(320),
  campo_cancer_de_numero_orden_73 character varying(320),
  campo_cancer_de_numero_orden_74 character varying(320),
  campo_cancer_de_numero_orden_75 character varying(320),
  campo_cancer_de_numero_orden_76 character varying(320),
  campo_cancer_de_numero_orden_77 character varying(320),
  campo_cancer_de_numero_orden_78 character varying(320),
  campo_cancer_de_numero_orden_79 character varying(320),
  campo_cancer_de_numero_orden_80 character varying(320),
  campo_cancer_de_numero_orden_81 character varying(320),
  campo_cancer_de_numero_orden_82 character varying(320),
  campo_cancer_de_numero_orden_83 character varying(320),
  campo_cancer_de_numero_orden_84 character varying(320),
  campo_cancer_de_numero_orden_85 character varying(320),
  campo_cancer_de_numero_orden_86 character varying(320),
  campo_cancer_de_numero_orden_87 character varying(320),
  campo_cancer_de_numero_orden_88 character varying(320),
  campo_cancer_de_numero_orden_89 character varying(320),
  campo_cancer_de_numero_orden_90 character varying(320),
  campo_cancer_de_numero_orden_91 character varying(320),
  campo_cancer_de_numero_orden_92 character varying(320),
  campo_cancer_de_numero_orden_93 character varying(320),
  campo_cancer_de_numero_orden_94 character varying(320),
  campo_cancer_de_numero_orden_95 character varying(320),
  campo_cancer_de_numero_orden_96 character varying(320),
  campo_cancer_de_numero_orden_97 character varying(320),
  campo_cancer_de_numero_orden_98 character varying(320),
  campo_cancer_de_numero_orden_99 character varying(320),
  campo_cancer_de_numero_orden_100 character varying(320),
  campo_cancer_de_numero_orden_101 character varying(320),
  campo_cancer_de_numero_orden_102 character varying(320),
  campo_cancer_de_numero_orden_103 character varying(320),
  campo_cancer_de_numero_orden_104 character varying(320),
  campo_cancer_de_numero_orden_105 character varying(320),
  campo_cancer_de_numero_orden_106 character varying(320),
  campo_cancer_de_numero_orden_107 character varying(320),
  campo_cancer_de_numero_orden_108 character varying(320),
  campo_cancer_de_numero_orden_109 character varying(320),
  campo_cancer_de_numero_orden_110 character varying(320),
  campo_cancer_de_numero_orden_111 character varying(320),
  campo_cancer_de_numero_orden_112 character varying(320),
  campo_cancer_de_numero_orden_113 character varying(320),
  campo_cancer_de_numero_orden_114 character varying(320),
  campo_cancer_de_numero_orden_115 character varying(320),
  campo_cancer_de_numero_orden_116 character varying(320),
  campo_cancer_de_numero_orden_117 character varying(320),
  campo_cancer_de_numero_orden_118 character varying(320),
  campo_cancer_de_numero_orden_119 character varying(320),
  campo_cancer_de_numero_orden_120 character varying(320),
  campo_cancer_de_numero_orden_121 character varying(320),
  campo_cancer_de_numero_orden_122 character varying(320),
  campo_cancer_de_numero_orden_123 character varying(320),
  campo_cancer_de_numero_orden_124 character varying(320),
  campo_cancer_de_numero_orden_125 character varying(320),
  campo_cancer_de_numero_orden_126 character varying(320),
  campo_cancer_de_numero_orden_127 character varying(320),
  campo_cancer_de_numero_orden_128 character varying(320),
  campo_cancer_de_numero_orden_129 character varying(320),
  campo_cancer_de_numero_orden_130 character varying(320),
  campo_cancer_de_numero_orden_131 character varying(320),
  campo_cancer_de_numero_orden_132 character varying(320),
  campo_cancer_de_numero_orden_133 character varying(320),
  campo_cancer_de_numero_orden_134 character varying(320),
  campo_cancer_de_numero_orden_135 character varying(320),
  campo_cancer_de_numero_orden_136 character varying(320),
  campo_cancer_de_numero_orden_137 character varying(320),
  campo_cancer_de_numero_orden_138 character varying(320),
  campo_cancer_de_numero_orden_139 character varying(320),
  campo_cancer_de_numero_orden_140 character varying(320),
  campo_cancer_de_numero_orden_141 character varying(320),
  campo_cancer_de_numero_orden_142 character varying(320),
  campo_cancer_de_numero_orden_143 character varying(320),
  campo_cancer_de_numero_orden_144 character varying(320),
  campo_cancer_de_numero_orden_145 character varying(320),
  campo_cancer_de_numero_orden_146 character varying(320),
  campo_cancer_de_numero_orden_147 character varying(320),
  campo_cancer_de_numero_orden_148 character varying(320),
  campo_cancer_de_numero_orden_149 character varying(320),
  campo_cancer_de_numero_orden_150 character varying(320),
  campo_cancer_de_numero_orden_151 character varying(320),
  campo_cancer_de_numero_orden_152 character varying(320),
  campo_cancer_de_numero_orden_153 character varying(320),
  campo_cancer_de_numero_orden_154 character varying(320),
  campo_cancer_de_numero_orden_155 character varying(320),
  campo_cancer_de_numero_orden_156 character varying(320),
  campo_cancer_de_numero_orden_157 character varying(320),
  campo_cancer_de_numero_orden_158 character varying(320),
  campo_cancer_de_numero_orden_159 character varying(320),
  campo_cancer_de_numero_orden_160 character varying(320),
  campo_cancer_de_numero_orden_161 character varying(320),
  campo_cancer_de_numero_orden_162 character varying(320),
  campo_cancer_de_numero_orden_163 character varying(320),
  campo_cancer_de_numero_orden_164 character varying(320),
  campo_cancer_de_numero_orden_165 character varying(320),
  campo_cancer_de_numero_orden_166 character varying(320),
  campo_cancer_de_numero_orden_167 character varying(320),
  campo_cancer_de_numero_orden_168 character varying(320),
  campo_cancer_de_numero_orden_169 character varying(320),
  campo_cancer_de_numero_orden_170 character varying(320),
  campo_cancer_de_numero_orden_171 character varying(320),
  campo_cancer_de_numero_orden_172 character varying(320),
  campo_cancer_de_numero_orden_173 character varying(320),
  campo_cancer_de_numero_orden_174 character varying(320),
  campo_cancer_de_numero_orden_175 character varying(320),
  campo_cancer_de_numero_orden_176 character varying(320),
  campo_cancer_de_numero_orden_177 character varying(320),
  campo_cancer_de_numero_orden_178 character varying(320),
  campo_cancer_de_numero_orden_179 character varying(320),
  campo_cancer_de_numero_orden_180 character varying(320),
  campo_cancer_de_numero_orden_181 character varying(320),
  campo_cancer_de_numero_orden_182 character varying(320),
  campo_cancer_de_numero_orden_183 character varying(320),
  campo_cancer_de_numero_orden_184 character varying(320),
  campo_cancer_de_numero_orden_185 character varying(320),
  campo_cancer_de_numero_orden_186 character varying(320),
  campo_cancer_de_numero_orden_187 character varying(320),
  campo_cancer_de_numero_orden_188 character varying(320),
  campo_cancer_de_numero_orden_189 character varying(320),
  campo_cancer_de_numero_orden_190 character varying(320),
  campo_cancer_de_numero_orden_191 character varying(320),
  campo_cancer_de_numero_orden_192 character varying(320),
  campo_cancer_de_numero_orden_193 character varying(320),
  campo_cancer_de_numero_orden_194 character varying(320),
  campo_cancer_de_numero_orden_195 character varying(320),
  campo_cancer_de_numero_orden_196 character varying(320),
  campo_cancer_de_numero_orden_197 character varying(320),
  campo_cancer_de_numero_orden_198 character varying(320),
  campo_cancer_de_numero_orden_199 character varying(320),
  campo_cancer_de_numero_orden_200 character varying(320),
  campo_cancer_de_numero_orden_201 character varying(320),
  campo_cancer_de_numero_orden_202 character varying(320),
  campo_cancer_de_numero_orden_203 character varying(320),
  campo_cancer_de_numero_orden_204 character varying(320),
  campo_cancer_de_numero_orden_205 character varying(320),
  campo_cancer_de_numero_orden_206 character varying(320),
  campo_cancer_de_numero_orden_207 character varying(320),
  campo_cancer_de_numero_orden_208 character varying(320),
  campo_cancer_de_numero_orden_209 character varying(320),
  campo_cancer_de_numero_orden_210 character varying(320),  
  PRIMARY KEY (cod_prestador_servicios_salud, codigo_eapb, fecha_inicio_periodo, fecha_de_corte, numero_fila, nombre_archivo, fecha_y_hora_validacion)
);